// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mobile_service_admin.proto

package mobile_service_grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ConfigJson struct {
	Body                 string   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigJson) Reset()         { *m = ConfigJson{} }
func (m *ConfigJson) String() string { return proto.CompactTextString(m) }
func (*ConfigJson) ProtoMessage()    {}
func (*ConfigJson) Descriptor() ([]byte, []int) {
	return fileDescriptor_mobile_service_admin_91b047afa25f7cc6, []int{0}
}
func (m *ConfigJson) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigJson.Unmarshal(m, b)
}
func (m *ConfigJson) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigJson.Marshal(b, m, deterministic)
}
func (dst *ConfigJson) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigJson.Merge(dst, src)
}
func (m *ConfigJson) XXX_Size() int {
	return xxx_messageInfo_ConfigJson.Size(m)
}
func (m *ConfigJson) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigJson.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigJson proto.InternalMessageInfo

func (m *ConfigJson) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type SyncGateway struct {
	SyncGatewayUUID      string   `protobuf:"bytes,1,opt,name=SyncGatewayUUID,proto3" json:"SyncGatewayUUID,omitempty"`
	LastSeenTimestamp    string   `protobuf:"bytes,2,opt,name=LastSeenTimestamp,proto3" json:"LastSeenTimestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncGateway) Reset()         { *m = SyncGateway{} }
func (m *SyncGateway) String() string { return proto.CompactTextString(m) }
func (*SyncGateway) ProtoMessage()    {}
func (*SyncGateway) Descriptor() ([]byte, []int) {
	return fileDescriptor_mobile_service_admin_91b047afa25f7cc6, []int{1}
}
func (m *SyncGateway) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncGateway.Unmarshal(m, b)
}
func (m *SyncGateway) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncGateway.Marshal(b, m, deterministic)
}
func (dst *SyncGateway) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncGateway.Merge(dst, src)
}
func (m *SyncGateway) XXX_Size() int {
	return xxx_messageInfo_SyncGateway.Size(m)
}
func (m *SyncGateway) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncGateway.DiscardUnknown(m)
}

var xxx_messageInfo_SyncGateway proto.InternalMessageInfo

func (m *SyncGateway) GetSyncGatewayUUID() string {
	if m != nil {
		return m.SyncGatewayUUID
	}
	return ""
}

func (m *SyncGateway) GetLastSeenTimestamp() string {
	if m != nil {
		return m.LastSeenTimestamp
	}
	return ""
}

type SyncGateways struct {
	Items                []*SyncGateway `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SyncGateways) Reset()         { *m = SyncGateways{} }
func (m *SyncGateways) String() string { return proto.CompactTextString(m) }
func (*SyncGateways) ProtoMessage()    {}
func (*SyncGateways) Descriptor() ([]byte, []int) {
	return fileDescriptor_mobile_service_admin_91b047afa25f7cc6, []int{2}
}
func (m *SyncGateways) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncGateways.Unmarshal(m, b)
}
func (m *SyncGateways) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncGateways.Marshal(b, m, deterministic)
}
func (dst *SyncGateways) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncGateways.Merge(dst, src)
}
func (m *SyncGateways) XXX_Size() int {
	return xxx_messageInfo_SyncGateways.Size(m)
}
func (m *SyncGateways) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncGateways.DiscardUnknown(m)
}

var xxx_messageInfo_SyncGateways proto.InternalMessageInfo

func (m *SyncGateways) GetItems() []*SyncGateway {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*ConfigJson)(nil), "mobile_service_grpc.ConfigJson")
	proto.RegisterType((*SyncGateway)(nil), "mobile_service_grpc.SyncGateway")
	proto.RegisterType((*SyncGateways)(nil), "mobile_service_grpc.SyncGateways")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MobileServiceAdminClient is the client API for MobileServiceAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MobileServiceAdminClient interface {
	ImportConfig(ctx context.Context, in *ConfigJson, opts ...grpc.CallOption) (*Empty, error)
	ExportConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ConfigJson, error)
	ListSyncGateways(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SyncGateways, error)
}

type mobileServiceAdminClient struct {
	cc *grpc.ClientConn
}

func NewMobileServiceAdminClient(cc *grpc.ClientConn) MobileServiceAdminClient {
	return &mobileServiceAdminClient{cc}
}

func (c *mobileServiceAdminClient) ImportConfig(ctx context.Context, in *ConfigJson, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/mobile_service_grpc.MobileServiceAdmin/ImportConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mobileServiceAdminClient) ExportConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ConfigJson, error) {
	out := new(ConfigJson)
	err := c.cc.Invoke(ctx, "/mobile_service_grpc.MobileServiceAdmin/ExportConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mobileServiceAdminClient) ListSyncGateways(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SyncGateways, error) {
	out := new(SyncGateways)
	err := c.cc.Invoke(ctx, "/mobile_service_grpc.MobileServiceAdmin/ListSyncGateways", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MobileServiceAdminServer is the server API for MobileServiceAdmin service.
type MobileServiceAdminServer interface {
	ImportConfig(context.Context, *ConfigJson) (*Empty, error)
	ExportConfig(context.Context, *Empty) (*ConfigJson, error)
	ListSyncGateways(context.Context, *Empty) (*SyncGateways, error)
}

func RegisterMobileServiceAdminServer(s *grpc.Server, srv MobileServiceAdminServer) {
	s.RegisterService(&_MobileServiceAdmin_serviceDesc, srv)
}

func _MobileServiceAdmin_ImportConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigJson)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MobileServiceAdminServer).ImportConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mobile_service_grpc.MobileServiceAdmin/ImportConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MobileServiceAdminServer).ImportConfig(ctx, req.(*ConfigJson))
	}
	return interceptor(ctx, in, info, handler)
}

func _MobileServiceAdmin_ExportConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MobileServiceAdminServer).ExportConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mobile_service_grpc.MobileServiceAdmin/ExportConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MobileServiceAdminServer).ExportConfig(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MobileServiceAdmin_ListSyncGateways_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MobileServiceAdminServer).ListSyncGateways(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mobile_service_grpc.MobileServiceAdmin/ListSyncGateways",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MobileServiceAdminServer).ListSyncGateways(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _MobileServiceAdmin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mobile_service_grpc.MobileServiceAdmin",
	HandlerType: (*MobileServiceAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ImportConfig",
			Handler:    _MobileServiceAdmin_ImportConfig_Handler,
		},
		{
			MethodName: "ExportConfig",
			Handler:    _MobileServiceAdmin_ExportConfig_Handler,
		},
		{
			MethodName: "ListSyncGateways",
			Handler:    _MobileServiceAdmin_ListSyncGateways_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mobile_service_admin.proto",
}

func init() {
	proto.RegisterFile("mobile_service_admin.proto", fileDescriptor_mobile_service_admin_91b047afa25f7cc6)
}

var fileDescriptor_mobile_service_admin_91b047afa25f7cc6 = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xc1, 0x4b, 0xfb, 0x30,
	0x14, 0xc7, 0xdb, 0xfd, 0x7e, 0x0a, 0xbe, 0x15, 0xd4, 0xe7, 0xa5, 0xe4, 0x62, 0xcd, 0xa9, 0x07,
	0xe9, 0x61, 0x82, 0x77, 0xd1, 0x29, 0x93, 0xed, 0xb2, 0xba, 0xf3, 0x48, 0xbb, 0x38, 0x02, 0x26,
	0x2f, 0x34, 0x41, 0xed, 0x5f, 0xe0, 0xbf, 0x2d, 0x6b, 0x07, 0xd6, 0x59, 0xb6, 0x5b, 0x92, 0xf7,
	0xc9, 0x27, 0x7c, 0xbf, 0x01, 0xa6, 0xa9, 0x50, 0x6f, 0x72, 0xe9, 0x64, 0xf5, 0xae, 0x4a, 0xb9,
	0x14, 0x2b, 0xad, 0x4c, 0x66, 0x2b, 0xf2, 0x84, 0x17, 0x3b, 0xb3, 0x75, 0x65, 0x4b, 0x16, 0x95,
	0xa4, 0x35, 0x6d, 0x11, 0x9e, 0x00, 0xdc, 0x93, 0x79, 0x55, 0xeb, 0x67, 0x47, 0x06, 0x11, 0xfe,
	0x17, 0xb4, 0xaa, 0xe3, 0x30, 0x09, 0xd3, 0x93, 0x79, 0xb3, 0xe6, 0x12, 0x86, 0x79, 0x6d, 0xca,
	0x27, 0xe1, 0xe5, 0x87, 0xa8, 0x31, 0x85, 0xd3, 0xce, 0x76, 0xb1, 0x98, 0x3c, 0x6c, 0xe9, 0xdd,
	0x63, 0xbc, 0x86, 0xf3, 0xa9, 0x70, 0x3e, 0x97, 0xd2, 0xbc, 0x28, 0x2d, 0x9d, 0x17, 0xda, 0xc6,
	0x83, 0x86, 0xfd, 0x3b, 0xe0, 0x8f, 0x10, 0x75, 0x04, 0x0e, 0x6f, 0xe1, 0x48, 0x79, 0xa9, 0x5d,
	0x1c, 0x26, 0xff, 0xd2, 0xe1, 0x28, 0xc9, 0x7a, 0xb2, 0x64, 0x9d, 0x1b, 0xf3, 0x16, 0x1f, 0x7d,
	0x0d, 0x00, 0x67, 0x0d, 0x9a, 0xb7, 0xe4, 0xdd, 0xa6, 0x10, 0x9c, 0x41, 0x34, 0xd1, 0x96, 0x2a,
	0xdf, 0xa6, 0xc5, 0xcb, 0x5e, 0xdf, 0x4f, 0x15, 0x8c, 0xf5, 0x02, 0x63, 0x6d, 0x7d, 0xcd, 0x83,
	0x8d, 0x6e, 0xfc, 0xd9, 0xd1, 0xed, 0xa1, 0xd9, 0xa1, 0xa7, 0x78, 0x80, 0x39, 0x9c, 0x4d, 0x95,
	0xf3, 0xbf, 0x0a, 0xd8, 0xa7, 0xbc, 0x3a, 0xd4, 0x86, 0xe3, 0x41, 0x71, 0xdc, 0xfc, 0xf0, 0xcd,
	0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xad, 0xe3, 0xf0, 0x4d, 0x22, 0x02, 0x00, 0x00,
}
